### ISSUE TITLE
Selenide is not complying to the Page Fragment pattern

### ISSUE THREAD

**Issue by espaciomore** [selenide-examples/google#2]
In the classic Page Object model one can find the Page Fragment pattern useful when the page contains too many element that can be separated by modules or fragments.

So, If I have the following PO:
```java
public class GooglePage {
  @FindBy(how = How.ID, using = "rso")
  public GoogleSearchResultsFragment searchResults;
}

public class GoogleSearchResultsFragment {
  @FindBy(how = How.CSS, using = "h3 a")
  public SelenideElement resultHeader;
}
```

I would get a `java.lang.NullPointerException` If I try to do the following:
```java
public class GoogleTest extends BaseTest {
  public void test_that_user_can_see_google_search_result_header() {
    googleSearchFor("Selenide");
    page(GooglePage.class).searchResults.resultHeader.shouldBe(Condition.visible);
  }
}
```
```

**Comment by espaciomore** [comment]
In order to get it to work with Selenide architecture I had to do the following:
```java
public class GooglePage {
  public GoogleSearchResultsFragment searchResults = page(GoogleSearchResultsFragment.class);
}
```

It works great but the syntax is wrong. Maybe It would make more sense If Selenide had an alias for `page` as `fragment` or perhaps create a new object for fragments.

**Comment by asolntsev** [comment]
@espaciomore thank you for reporting the issue. I was sure that your code should work without need to call page(GoogleSearchResultsFragment.class)

I need to investigate it.

**Comment by asolntsev** [comment]
@espaciomore Well, I found the problem cause. You have to extend `ElementsContainer`:

```java
class GoogleSearchResultsFragment extends ElementsContainer {
  @FindBy(how = How.CSS, using = "h3 a")
  public SelenideElement resultHeader;
}
```
